### ISSUE TITLE
数据页面需配合datasets具体文件动态显示内容

### ISSUE THREAD

**Issue by Feng-Gao** [SODAChallenges/SODAChallenges.github.io#1]
目前数据页面新增的“相关城市问题”、“解决方案”为hard coded，应当能够根据对应的datasets文件，自动判定是否显示内容以及显示什么内容

**Comment by lxyu0405** [comment]
准备先把页面布局框架，静态效果确定。然后再向其中根据数据添加“动态”内容。

**Comment by Feng-Gao** [comment]
@lxyu0405 好的，我同步在研究对dataset scheme的拓展了，基本上增加进一个城市问题大类（四大板块）问题不大，其他内容还未进来。但放入四大板块的属性后，datasets的列表页面，左侧第一个现在是城市问题的筛选（即四大板块筛选），目前还不能很好工作，我本地正在尝试对这个问题进行改良，目前另外碰到一个问题是，左侧过滤的内容目前只能是英文，中文会被它系统的js过滤无法添加到url里。

**Comment by lxyu0405** [comment]
嗯，是的，我之前也发现了，中文的属性没有办法作为reference关联到其他数据。datasets的筛选页，我也在研究。因为我想把城市问题的列表展示也做成类似。
datasets的结构是左边筛选，右边出现结果。我想用同样的筛选机制。在challenges页面上，使用上下结构，上面筛选，下面出现结果。上面两个select选择框，分别“问题所属版块”和“年份”，下面展示筛选结果的方块。

**Comment by Feng-Gao** [comment]
@lxyu0405 

我没有创建单独issue来解决问题了，我这边整体说明下我目前提交进来的新commit做的几点修正
1. 对datascheme做了延展，目前创建了soda-data.yml这个新scheme，并且在config启用了。这个scheme里为数据添加了一个新属性challenge_category，其取值为四大创新板块，即每个数据可属于一个或多个创新板块（即用于现有界面上显示的城市问题过滤器部分）
2. 现在测试数据集都启用了这个新的属性，放入了测试数据
3. 数据清单页面的左侧筛选器部分，我完成了修正，已经可以正常按照三个不同属性过滤了。
4. 中文的问题修复了，问题在于util.js文件里的slugify函数，本身只支持英文，所以把中文字符用正则过滤掉了，现在把中文支持加上了。

目前数据清单页面问题应该ok了，我后面再看看数据详情页面，怎么动态。你先弄城市问题的列表页面吧。

**Comment by lxyu0405** [comment]
嗯嗯，厉害了！我pull下来看看

**Comment by Feng-Gao** [comment]
对了，原先的开发本身是用了webpack把js打包进了bundle.js，所以js各源文件的修改完成后，需要用webpack -p 重新打包进bundle里，否则还是不会加载到修改内容。这个具体webpack我不太熟悉，所以不太清楚开发情况下，和jekyll服务器本身怎么配合，可以不用每次先打包再测试，最好是改了js直接用jekyll server能够看到效果，最后上线的时候才打包成bundle。

**Comment by lxyu0405** [comment]
OK
